version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Asia/Hong_Kong
  open-pull-requests-limit: 99
  reviewers:
    - kristian-nst
