// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
    "/profiles/[id]": InferRoute<import("./src/app/profiles/[id]/routeType").RouteType>;
  }

  interface StaticRouter {
    "/authentication/callback": StaticRoute;
    "/authentication/log-out": StaticRoute;
    "/authentication/sign-up": StaticRoute;
    "/authentication/success": StaticRoute;
    "/campaigns": StaticRoute;
    "/": StaticRoute;
    "/portfolio": StaticRoute;
    "/wallet": StaticRoute;
  }
}
