/* eslint-disable import/imports-first */
import './globals.css'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { type ReactElement, type ReactNode } from 'react'

import Providers from '~/providers'

const gilroyRegular = localFont({
  src: '../../public/media/fonts/Gilroy-Regular.woff2',
  display: 'swap',
  variable: '--font-gilroy-regular',
})

const gilroyBold = localFont({
  src: '../../public/media/fonts/Gilroy-Bold.woff2',
  display: 'swap',
  variable: '--font-gilroy-bold',
})

const clashGroteskBold = localFont({
  src: '../../public/media/fonts/ClashGrotesk-Bold.woff2',
  display: 'swap',
  variable: '--font-clash-grotesk-bold',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>): ReactElement {
  return (
    <html lang="en">
      <body
        className={`font-gilroy-regular leading-tight antialiased ${gilroyRegular.variable} ${gilroyBold.variable} ${clashGroteskBold.variable}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
